development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:bfed8010275c8c0d0643c69a47ca0999@spinyfin.redistogo.com:11208/
  channel_prefix: away-we-go_production
